# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1100, 615)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidgetDataDimension = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetDataDimension.sizePolicy().hasHeightForWidth())
        self.tabWidgetDataDimension.setSizePolicy(sizePolicy)
        self.tabWidgetDataDimension.setMinimumSize(QtCore.QSize(0, 250))
        self.tabWidgetDataDimension.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidgetDataDimension.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidgetDataDimension.setAcceptDrops(True)
        self.tabWidgetDataDimension.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidgetDataDimension.setDocumentMode(True)
        self.tabWidgetDataDimension.setTabsClosable(False)
        self.tabWidgetDataDimension.setMovable(False)
        self.tabWidgetDataDimension.setTabBarAutoHide(False)
        self.tabWidgetDataDimension.setObjectName("tabWidgetDataDimension")
        self.tabDataObjects = QtWidgets.QWidget()
        self.tabDataObjects.setObjectName("tabDataObjects")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tabDataObjects)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayoutTableDataBase = QtWidgets.QHBoxLayout()
        self.horizontalLayoutTableDataBase.setObjectName("horizontalLayoutTableDataBase")
        self.gridLayout_9.addLayout(self.horizontalLayoutTableDataBase, 0, 3, 1, 1)
        self.tabWidgetDataDimension.addTab(self.tabDataObjects, "")
        self.tabProtocol = QtWidgets.QWidget()
        self.tabProtocol.setObjectName("tabProtocol")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabProtocol)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textBrowserProtocol = QtWidgets.QTextBrowser(self.tabProtocol)
        self.textBrowserProtocol.setEnabled(False)
        self.textBrowserProtocol.setFrameShape(QtWidgets.QFrame.Panel)
        self.textBrowserProtocol.setObjectName("textBrowserProtocol")
        self.gridLayout_7.addWidget(self.textBrowserProtocol, 0, 0, 1, 1)
        self.tabWidgetDataDimension.addTab(self.tabProtocol, "")
        self.gridLayout.addWidget(self.tabWidgetDataDimension, 1, 1, 1, 1)
        self.tabWidgetDataDim = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetDataDim.setEnabled(True)
        self.tabWidgetDataDim.setMaximumSize(QtCore.QSize(180, 280))
        self.tabWidgetDataDim.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidgetDataDim.setAcceptDrops(True)
        self.tabWidgetDataDim.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidgetDataDim.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidgetDataDim.setDocumentMode(True)
        self.tabWidgetDataDim.setObjectName("tabWidgetDataDim")
        self.tab1D = QtWidgets.QWidget()
        self.tab1D.setObjectName("tab1D")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab1D)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayoutTree1Dim = QtWidgets.QHBoxLayout()
        self.horizontalLayoutTree1Dim.setObjectName("horizontalLayoutTree1Dim")
        self.horizontalLayout.addLayout(self.horizontalLayoutTree1Dim)
        self.tabWidgetDataDim.addTab(self.tab1D, "")
        self.tab2D = QtWidgets.QWidget()
        self.tab2D.setObjectName("tab2D")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab2D)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayoutTree2Dim = QtWidgets.QHBoxLayout()
        self.horizontalLayoutTree2Dim.setObjectName("horizontalLayoutTree2Dim")
        self.gridLayout_3.addLayout(self.horizontalLayoutTree2Dim, 0, 0, 1, 1)
        self.tabWidgetDataDim.addTab(self.tab2D, "")
        self.gridLayout.addWidget(self.tabWidgetDataDim, 1, 0, 1, 1)
        self.tabWidgetDataAnalysis = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetDataAnalysis.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetDataAnalysis.sizePolicy().hasHeightForWidth())
        self.tabWidgetDataAnalysis.setSizePolicy(sizePolicy)
        self.tabWidgetDataAnalysis.setMinimumSize(QtCore.QSize(0, 320))
        self.tabWidgetDataAnalysis.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidgetDataAnalysis.setAcceptDrops(True)
        self.tabWidgetDataAnalysis.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidgetDataAnalysis.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidgetDataAnalysis.setDocumentMode(True)
        self.tabWidgetDataAnalysis.setObjectName("tabWidgetDataAnalysis")
        self.tabVector = QtWidgets.QWidget()
        self.tabVector.setObjectName("tabVector")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabVector)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidgetPrimaryStatAnalysis = QtWidgets.QTabWidget(self.tabVector)
        self.tabWidgetPrimaryStatAnalysis.setEnabled(False)
        self.tabWidgetPrimaryStatAnalysis.setAcceptDrops(True)
        self.tabWidgetPrimaryStatAnalysis.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidgetPrimaryStatAnalysis.setDocumentMode(True)
        self.tabWidgetPrimaryStatAnalysis.setObjectName("tabWidgetPrimaryStatAnalysis")
        self.tabPrimaryAnalys = QtWidgets.QWidget()
        self.tabPrimaryAnalys.setObjectName("tabPrimaryAnalys")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabPrimaryAnalys)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayoutHistogram = QtWidgets.QGridLayout()
        self.gridLayoutHistogram.setObjectName("gridLayoutHistogram")
        self.gridLayout_4.addLayout(self.gridLayoutHistogram, 0, 0, 1, 1)
        self.lineSeparatorMatplotWIdgets = QtWidgets.QFrame(self.tabPrimaryAnalys)
        self.lineSeparatorMatplotWIdgets.setAcceptDrops(True)
        self.lineSeparatorMatplotWIdgets.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineSeparatorMatplotWIdgets.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineSeparatorMatplotWIdgets.setObjectName("lineSeparatorMatplotWIdgets")
        self.gridLayout_4.addWidget(self.lineSeparatorMatplotWIdgets, 0, 1, 1, 1)
        self.gridLayoutDensityFunction = QtWidgets.QGridLayout()
        self.gridLayoutDensityFunction.setObjectName("gridLayoutDensityFunction")
        self.gridLayout_4.addLayout(self.gridLayoutDensityFunction, 0, 2, 1, 1)
        self.tabWidgetPrimaryStatAnalysis.addTab(self.tabPrimaryAnalys, "")
        self.tabProbabilityGrid = QtWidgets.QWidget()
        self.tabProbabilityGrid.setObjectName("tabProbabilityGrid")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabProbabilityGrid)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayoutProbabilityGrid = QtWidgets.QGridLayout()
        self.gridLayoutProbabilityGrid.setObjectName("gridLayoutProbabilityGrid")
        self.gridLayout_5.addLayout(self.gridLayoutProbabilityGrid, 0, 0, 1, 1)
        self.tabWidgetPrimaryStatAnalysis.addTab(self.tabProbabilityGrid, "")
        self.tabHomogenityExpSample = QtWidgets.QWidget()
        self.tabHomogenityExpSample.setObjectName("tabHomogenityExpSample")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabHomogenityExpSample)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBoxDistributionFisrtExp = QtWidgets.QComboBox(self.tabHomogenityExpSample)
        self.comboBoxDistributionFisrtExp.setObjectName("comboBoxDistributionFisrtExp")
        self.comboBoxDistributionFisrtExp.addItem("")
        self.comboBoxDistributionFisrtExp.addItem("")
        self.comboBoxDistributionFisrtExp.addItem("")
        self.gridLayout_6.addWidget(self.comboBoxDistributionFisrtExp, 0, 0, 1, 1)
        self.lineSeparatorFirstExp = QtWidgets.QFrame(self.tabHomogenityExpSample)
        self.lineSeparatorFirstExp.setFrameShape(QtWidgets.QFrame.VLine)
        self.lineSeparatorFirstExp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineSeparatorFirstExp.setObjectName("lineSeparatorFirstExp")
        self.gridLayout_6.addWidget(self.lineSeparatorFirstExp, 0, 1, 3, 1)
        self.comboBoxDistributionSecondExp = QtWidgets.QComboBox(self.tabHomogenityExpSample)
        self.comboBoxDistributionSecondExp.setObjectName("comboBoxDistributionSecondExp")
        self.comboBoxDistributionSecondExp.addItem("")
        self.comboBoxDistributionSecondExp.addItem("")
        self.comboBoxDistributionSecondExp.addItem("")
        self.gridLayout_6.addWidget(self.comboBoxDistributionSecondExp, 0, 2, 1, 1)
        self.tableWidgetParametersDistrFisrtExp = QtWidgets.QTableWidget(self.tabHomogenityExpSample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetParametersDistrFisrtExp.sizePolicy().hasHeightForWidth())
        self.tableWidgetParametersDistrFisrtExp.setSizePolicy(sizePolicy)
        self.tableWidgetParametersDistrFisrtExp.setMaximumSize(QtCore.QSize(16777215, 50))
        self.tableWidgetParametersDistrFisrtExp.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidgetParametersDistrFisrtExp.setObjectName("tableWidgetParametersDistrFisrtExp")
        self.tableWidgetParametersDistrFisrtExp.setColumnCount(0)
        self.tableWidgetParametersDistrFisrtExp.setRowCount(0)
        self.gridLayout_6.addWidget(self.tableWidgetParametersDistrFisrtExp, 1, 0, 1, 1)
        self.tableWidgetParameterSecondExp = QtWidgets.QTableWidget(self.tabHomogenityExpSample)
        self.tableWidgetParameterSecondExp.setMaximumSize(QtCore.QSize(16777215, 50))
        self.tableWidgetParameterSecondExp.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidgetParameterSecondExp.setObjectName("tableWidgetParameterSecondExp")
        self.tableWidgetParameterSecondExp.setColumnCount(0)
        self.tableWidgetParameterSecondExp.setRowCount(0)
        self.gridLayout_6.addWidget(self.tableWidgetParameterSecondExp, 1, 2, 1, 1)
        self.textEditResultFirstExp = QtWidgets.QTextEdit(self.tabHomogenityExpSample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditResultFirstExp.sizePolicy().hasHeightForWidth())
        self.textEditResultFirstExp.setSizePolicy(sizePolicy)
        self.textEditResultFirstExp.setMinimumSize(QtCore.QSize(0, 75))
        self.textEditResultFirstExp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEditResultFirstExp.setFrameShape(QtWidgets.QFrame.Panel)
        self.textEditResultFirstExp.setObjectName("textEditResultFirstExp")
        self.gridLayout_6.addWidget(self.textEditResultFirstExp, 2, 0, 1, 1)
        self.textEditResultSecondExp = QtWidgets.QTextEdit(self.tabHomogenityExpSample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditResultSecondExp.sizePolicy().hasHeightForWidth())
        self.textEditResultSecondExp.setSizePolicy(sizePolicy)
        self.textEditResultSecondExp.setMinimumSize(QtCore.QSize(0, 75))
        self.textEditResultSecondExp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEditResultSecondExp.setFrameShape(QtWidgets.QFrame.Panel)
        self.textEditResultSecondExp.setObjectName("textEditResultSecondExp")
        self.gridLayout_6.addWidget(self.textEditResultSecondExp, 2, 2, 1, 1)
        self.tabWidgetPrimaryStatAnalysis.addTab(self.tabHomogenityExpSample, "")
        self.tabHomogenityExpManySamples = QtWidgets.QWidget()
        self.tabHomogenityExpManySamples.setObjectName("tabHomogenityExpManySamples")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tabHomogenityExpManySamples)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pushButtonModelDataHomogeneitySamples = QtWidgets.QPushButton(self.tabHomogenityExpManySamples)
        self.pushButtonModelDataHomogeneitySamples.setObjectName("pushButtonModelDataHomogeneitySamples")
        self.gridLayout_8.addWidget(self.pushButtonModelDataHomogeneitySamples, 4, 0, 1, 3)
        self.spinBoxCountHomogeneitySamples = QtWidgets.QSpinBox(self.tabHomogenityExpManySamples)
        self.spinBoxCountHomogeneitySamples.setObjectName("spinBoxCountHomogeneitySamples")
        self.gridLayout_8.addWidget(self.spinBoxCountHomogeneitySamples, 0, 0, 1, 1)
        self.tableWidgetParametersHomogeneitySamples = QtWidgets.QTableWidget(self.tabHomogenityExpManySamples)
        self.tableWidgetParametersHomogeneitySamples.setFrameShape(QtWidgets.QFrame.Panel)
        self.tableWidgetParametersHomogeneitySamples.setObjectName("tableWidgetParametersHomogeneitySamples")
        self.tableWidgetParametersHomogeneitySamples.setColumnCount(0)
        self.tableWidgetParametersHomogeneitySamples.setRowCount(0)
        self.gridLayout_8.addWidget(self.tableWidgetParametersHomogeneitySamples, 1, 0, 3, 3)
        self.labelCountSamples = QtWidgets.QLabel(self.tabHomogenityExpManySamples)
        self.labelCountSamples.setObjectName("labelCountSamples")
        self.gridLayout_8.addWidget(self.labelCountSamples, 0, 1, 1, 1)
        self.textEditResultHomogeneitySamples = QtWidgets.QTextEdit(self.tabHomogenityExpManySamples)
        self.textEditResultHomogeneitySamples.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textEditResultHomogeneitySamples.setFrameShape(QtWidgets.QFrame.Panel)
        self.textEditResultHomogeneitySamples.setObjectName("textEditResultHomogeneitySamples")
        self.gridLayout_8.addWidget(self.textEditResultHomogeneitySamples, 3, 4, 2, 1)
        self.pushButtonCheckHomogeneitySamples = QtWidgets.QPushButton(self.tabHomogenityExpManySamples)
        self.pushButtonCheckHomogeneitySamples.setObjectName("pushButtonCheckHomogeneitySamples")
        self.gridLayout_8.addWidget(self.pushButtonCheckHomogeneitySamples, 2, 4, 1, 1)
        self.comboBoxDisrtibutionHomogeneitySamples = QtWidgets.QComboBox(self.tabHomogenityExpManySamples)
        self.comboBoxDisrtibutionHomogeneitySamples.setObjectName("comboBoxDisrtibutionHomogeneitySamples")
        self.comboBoxDisrtibutionHomogeneitySamples.addItem("")
        self.comboBoxDisrtibutionHomogeneitySamples.addItem("")
        self.comboBoxDisrtibutionHomogeneitySamples.addItem("")
        self.gridLayout_8.addWidget(self.comboBoxDisrtibutionHomogeneitySamples, 0, 2, 1, 1)
        self.tableWidgetExperementDataHomogeneitySamples = QtWidgets.QTableWidget(self.tabHomogenityExpManySamples)
        self.tableWidgetExperementDataHomogeneitySamples.setObjectName("tableWidgetExperementDataHomogeneitySamples")
        self.tableWidgetExperementDataHomogeneitySamples.setColumnCount(0)
        self.tableWidgetExperementDataHomogeneitySamples.setRowCount(0)
        self.gridLayout_8.addWidget(self.tableWidgetExperementDataHomogeneitySamples, 0, 4, 2, 1)
        self.tabWidgetPrimaryStatAnalysis.addTab(self.tabHomogenityExpManySamples, "")
        self.gridLayout_2.addWidget(self.tabWidgetPrimaryStatAnalysis, 0, 0, 1, 1)
        self.tabWidgetDataAnalysis.addTab(self.tabVector, "")
        self.tabArea = QtWidgets.QWidget()
        self.tabArea.setObjectName("tabArea")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tabArea)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayoutCorreLationField = QtWidgets.QGridLayout()
        self.gridLayoutCorreLationField.setObjectName("gridLayoutCorreLationField")
        self.gridLayout_13.addLayout(self.gridLayoutCorreLationField, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.tabArea)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_13.addWidget(self.line, 0, 1, 1, 1)
        self.gridLayoutHistOfRelativeFrequencies = QtWidgets.QGridLayout()
        self.gridLayoutHistOfRelativeFrequencies.setObjectName("gridLayoutHistOfRelativeFrequencies")
        self.gridLayout_13.addLayout(self.gridLayoutHistOfRelativeFrequencies, 0, 2, 1, 1)
        self.tabWidgetDataAnalysis.addTab(self.tabArea, "")
        self.gridLayout.addWidget(self.tabWidgetDataAnalysis, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu_FIle = QtWidgets.QMenu(self.menuBar)
        self.menu_FIle.setObjectName("menu_FIle")
        self.menu_Help = QtWidgets.QMenu(self.menuBar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu_FIle.addAction(self.actionOpen)
        self.menu_FIle.addAction(self.actionSave)
        self.menu_FIle.addSeparator()
        self.menu_FIle.addAction(self.actionExit)
        self.menu_Help.addAction(self.actionAbout)
        self.menuBar.addAction(self.menu_FIle.menuAction())
        self.menuBar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidgetDataDimension.setCurrentIndex(0)
        self.tabWidgetDataDim.setCurrentIndex(0)
        self.tabWidgetDataAnalysis.setCurrentIndex(0)
        self.tabWidgetPrimaryStatAnalysis.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Статистичний аналіз"))
        self.tabWidgetDataDimension.setTabText(self.tabWidgetDataDimension.indexOf(self.tabDataObjects), _translate("MainWindow", "Об\'єкти"))
        self.tabWidgetDataDimension.setTabText(self.tabWidgetDataDimension.indexOf(self.tabProtocol), _translate("MainWindow", "Протокол"))
        self.tabWidgetDataDim.setTabText(self.tabWidgetDataDim.indexOf(self.tab1D), _translate("MainWindow", "1D"))
        self.tabWidgetDataDim.setTabText(self.tabWidgetDataDim.indexOf(self.tab2D), _translate("MainWindow", "2D"))
        self.tabWidgetPrimaryStatAnalysis.setTabText(self.tabWidgetPrimaryStatAnalysis.indexOf(self.tabPrimaryAnalys), _translate("MainWindow", "Первинний аналіз"))
        self.tabWidgetPrimaryStatAnalysis.setTabText(self.tabWidgetPrimaryStatAnalysis.indexOf(self.tabProbabilityGrid), _translate("MainWindow", "Ймовірнісна сітка"))
        self.comboBoxDistributionFisrtExp.setItemText(0, _translate("MainWindow", "Нормальний розподіл"))
        self.comboBoxDistributionFisrtExp.setItemText(1, _translate("MainWindow", "Експоненціальний розподіл"))
        self.comboBoxDistributionFisrtExp.setItemText(2, _translate("MainWindow", "Розподіл арксинуса"))
        self.comboBoxDistributionSecondExp.setItemText(0, _translate("MainWindow", "Нормальний розподіл"))
        self.comboBoxDistributionSecondExp.setItemText(1, _translate("MainWindow", "Експоненціальний розподіл"))
        self.comboBoxDistributionSecondExp.setItemText(2, _translate("MainWindow", "Розподіл арксинуса"))
        self.tabWidgetPrimaryStatAnalysis.setTabText(self.tabWidgetPrimaryStatAnalysis.indexOf(self.tabHomogenityExpSample), _translate("MainWindow", "Експерименти"))
        self.pushButtonModelDataHomogeneitySamples.setText(_translate("MainWindow", "Змоделювати вибірки"))
        self.labelCountSamples.setText(_translate("MainWindow", "Кількість вибірок"))
        self.pushButtonCheckHomogeneitySamples.setText(_translate("MainWindow", "Перевірити на однорідність"))
        self.comboBoxDisrtibutionHomogeneitySamples.setItemText(0, _translate("MainWindow", "Нормальний розподіл"))
        self.comboBoxDisrtibutionHomogeneitySamples.setItemText(1, _translate("MainWindow", "Експоненціальний розподіл"))
        self.comboBoxDisrtibutionHomogeneitySamples.setItemText(2, _translate("MainWindow", "Розподіл арксинуса"))
        self.tabWidgetPrimaryStatAnalysis.setTabText(self.tabWidgetPrimaryStatAnalysis.indexOf(self.tabHomogenityExpManySamples), _translate("MainWindow", "Перевірка однорідності множини вибірок"))
        self.tabWidgetDataAnalysis.setTabText(self.tabWidgetDataAnalysis.indexOf(self.tabVector), _translate("MainWindow", "Вектор"))
        self.tabWidgetDataAnalysis.setTabText(self.tabWidgetDataAnalysis.indexOf(self.tabArea), _translate("MainWindow", "Поверхня"))
        self.menu_FIle.setTitle(_translate("MainWindow", "&FIle"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSave.setText(_translate("MainWindow", "Save..."))
        self.actionExit.setText(_translate("MainWindow", "E&xit"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))

